#!/bin/sh
dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

selection=$(fzy -l20<"$dir/unicode.txt" | awk '{print $1}')
if [ ! -z "$selection" ]; then
    nohup wl-copy "$selection" 2>&1 >/dev/null
fi
